Isdg/Models/AwardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Isdg.Core.Data;

namespace Isdg.Models
{
    public class AwardViewModel
    {
        public Award Award { get; set; }
        public string UserName { get; set; }
    }
}

Isdg/Controllers/AwardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Isdg.Services.Information;
using Isdg.Core.Data;
using Isdg.Data;
using Ninject;
using Isdg.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using Isdg.Lib;
using log4net;
using Isdg.Services.Messages;
using System.IO;

namespace Isdg.Controllers
{    
    public class AwardController : BaseController
    {
        private readonly IAwardService awardService;

        public AwardController(IAwardService awardService, ILog log, IEmailSender emailSender)
            : base(log, emailSender) 
        {
            this.awardService = awardService;            
        }
                
        public ActionResult Index()
        {
            var awards = awardService.GetAllAwards();
            return View(awards.Select(ToAwardViewModel));
        }
        
        [HttpPost]
        public ActionResult CreateEditAward(Award model)
        {
            if (model.Id == 0)
            {                
                var currentDate = System.DateTime.Now;
                model.ModifiedDate = currentDate;
                model.AddedDate = currentDate;
                model.IP = Request.UserHostAddress;

                if (Request.Files.Count > 0)
                {
                    var path = SaveImage(Request.Files[0]);
                    model.PathToFirstPicture = path;
                }

                if (Request.Files.Count > 1)
                {
                    var secondPath = SaveImage(Request.Files[1]);
                    model.PathToSecondPicture = secondPath;
                }

                try
                {
                    model.UserId = User.Identity.GetUserId();
                    awardService.InsertAward(model);
                    return new JsonResult() { Data = new { success = true } };
                    //return RedirectToAction("Index");
                    //return PartialView("_Award", model);
                }
                catch (Exception ex)
                {
                    Log.Error(ex);
                    //ModelState.AddModelError("", "Failed to create award");
                    //return PartialView("_Award", null);                    
                    return new JsonResult() { Data = new { success = false, message = "Failed to create award" } };
                }                
            }
            else
            {
                try
                {
                    var editModel = awardService.GetAwardById(model.Id);
                    editModel.Heading = model.Heading;
                    editModel.Content = model.Content;                    
                    editModel.ModifiedDate = System.DateTime.Now;
                    editModel.IP = Request.UserHostAddress;
                    
                    if (Request.Files.Count > 0)
                    {
                        var path = SaveImage(Request.Files[0]);
                        editModel.PathToFirstPicture = path;
                    }

                    if (Request.Files.Count > 1)
                    {
                        var secondPath = SaveImage(Request.Files[1]);
                        editModel.PathToSecondPicture = secondPath;
                    }
                    
                    awardService.UpdateAward(editModel);                    
                    //return PartialView("_Award", editModel);
                    //return RedirectToAction("Index");
                    return new JsonResult() { Data = new { success = true } };
                }
                catch (Exception ex)
                {
                    Log.Error(ex);
                    //ModelState.AddModelError("", "Failed to update award");
                    //return PartialView("_Award", model);
                    return new JsonResult() { Data = new { success = false, message = "Failed to update award" } };
                }                
            }                     
        }

        [HttpPost]
        public ActionResult ConfirmDeleteAward(int awardId)
        {
            try
            {
                var model = awardService.GetAwardById(awardId);            
                awardService.DeleteAward(model);                
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            catch (Exception ex)
            {
                Log.Error(ex);
                ModelState.AddModelError("", "Failed to delete award");
                return PartialView("_Award", null);
            }            
        }
        
        private string SaveImage(HttpPostedFileBase file)
        {
            var extension = Path.GetExtension(file.FileName);
            var fileGuid = Guid.NewGuid();
            var fileName = fileGuid + extension;
            var path = Path.Combine(Server.MapPath("~/Content/Award/"), fileName);
            file.SaveAs(path);
            return Path.Combine("Content/Award/", fileName);
        }

        private AwardViewModel ToAwardViewModel(Award award)
        {
            return new AwardViewModel() 
            {
                Award = award,
                UserName = UserHelper.GetUserName(UserManager, award.UserId)
            };
        }
    }
}

Isdg/Views/Award/Index.cshtml
@using Isdg.Core.Data
@model IEnumerable<Isdg.Models.AwardViewModel>

@{
    ViewBag.Title = "Isaacs' Award";
}

<div class="section-header"><h2>@ViewBag.Title</h2></div>
<hr />
<p>The executive committee of the International Society of Dynamic Games decided in 2003 to establish a prize to recognize the &quot;outstanding contribution to the theory and applications of dynamic games&quot; of two scholars at each of its symposium, starting in 2004.  The prize was named after Rufus Isaacs, the acknowledged founding father of differential games.</p>

@if (Isdg.Lib.UserHelper.IsAdmin()) 
{
    @Html.Partial("_Create", new Award())
}
else
{
    <hr />
}
<div id="awards">
    @foreach (var item in Model)
    {        
        @Html.Partial("_Award", item)
    }
</div>

Isdg/Views/Award/_Award.cshtml
@using Isdg.Models
@model AwardViewModel
@if (Model == null)
{    
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })    
}
else 
{
    <div id="award_id_@Model.Award.Id">        
        <div class="award">        
            <div class="award__info"><span class="award__heading">@Model.Award.Heading</span>
                @if (Isdg.Lib.UserHelper.IsAdmin()) 
                {
                    <span class="links">                    
                        <a role="button" title="Edit award" onclick="showForm(this, 'award', 'award__edit')"><span class="fa fa-pencil"></span></a>                
                        <a role="button" title="Show award details" onclick="showForm(this, 'award', 'award__details')"><span class="fa fa-plus"></span></a>                    
                        <a role="button" title="Delete award" onclick="showForm(this, 'award__info', 'award__delete')"><span class="fa fa-trash"></span></a>                    
                    </span>
                }
                @Html.Partial("_Delete", Model.Award)
            </div>
            <div class="award__content">
                @if (!String.IsNullOrEmpty(Model.Award.PathToFirstPicture)) 
                {
                    if (!String.IsNullOrEmpty(Model.Award.PathToSecondPicture))
                    {
                        <div class="award__image"><img src="@Model.Award.PathToFirstPicture" /><img src="@Model.Award.PathToSecondPicture"/></div> 
                    }
                    else
                    {
                        <div class="award__image"><img src="@Model.Award.PathToFirstPicture" /></div> 
                    }
                }
                <div class="award__content">@Html.Raw(Model.Award.Content)
                    <div class="award__author">Published by @Model.UserName</div>
                </div>
            </div>                
            @Html.ValidationSummary(true, "", new { @class = "text-danger" }) 
            @Html.Partial("_Edit", Model.Award)
            @Html.Partial("_Details", Model.Award)
        </div>
    </div>        
}

Isdg/Views/Award/_Create.cshtml
@model Isdg.Core.Data.Award

@*@using (Ajax.BeginForm("CreateEditAward", "Award", new AjaxOptions()
{
    UpdateTargetId = "awards",
    InsertionMode = InsertionMode.InsertBefore,
    OnComplete = "bindCkeditor();hideSpinner()",
    OnBegin = "showSpinner()"
}, new { encType = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    *@
    <div class="form-horizontal">        
        <a role="button" class="award__add_open" onclick="openCreationForm('award')">Add Award <span class="fa fa-angle-double-down"></span></a>        
        <hr />
        <div class="award__form_add" style="display: none;">            
            <form class="award__new">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Heading, htmlAttributes: new { @class = "control-label col-md-1" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Heading, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Heading, "", new { @class = "text-danger" })
                </div>
            </div>                          
            <div class="form-group">
                @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-1" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                </div>
            </div>
            
            <div class="form-group image">
                <label class="control-label col-md-2">Choose first image</label>
                <input type="file" class="award__image-upload-first form-control" accept="image/*" />
            </div>
            
            <div class="form-group image">
                <label class="control-label col-md-2">Choose second image (not required)</label>
                <input type="file" class="award__image-upload-second form-control" accept="image/*" />
            </div>

            @*<div class="form-group">
                @Html.LabelFor(m => m.FirstImageUpload)
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.FirstImageUpload, new { type = "file" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.SecondImageUpload)
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.SecondImageUpload, new { type = "file" })
                </div>
            </div>*@

            @*<div class="form-group">
                <label class="control-label col-md-2">Choose first image</label>
                <input type="file" class="award__image-upload form-control" name="FirstImageUpload" data-index="0" accept="image/*" />
            </div>                          
            <div class="form-group">
                <label class="control-label col-md-2">Choose second image (not required)</label>
                <input type="file" class="award__image-upload form-control" name="SecondImageUpload" data-index="1" accept="image/*" />
            </div>*@

            <div class="form-group">
                <div class="col-md-offset-1 col-md-10">
                    <input type="button" value="Create" class="btn btn-default award__submit" /><i class="fa fa-spinner fa-spin fa-lg fa-fw hidden"></i>
                </div>
            </div>
            <div class="text-danger error-message hidden"></div>            
            </form>
            <hr />
        </div>                
        <a role="button" class="award__add_close" style="display: none;" onclick="closeCreationForm('award')">Add Award <span class="fa fa-angle-double-up"></span></a>        
    </div>    
@*}*@

Isdg/Views/Award/_Delete.cshtml
@model Isdg.Core.Data.Award

<span class="award__delete hidden">
@using (Ajax.BeginForm("ConfirmDeleteAward", "Award", new { awardId = Model.Id }, new AjaxOptions() { UpdateTargetId = "award_id_" + Model.Id}, new { @class = "form_inline text-danger" }))
{    
    <span class="delete_confirmation">Are you sure you want to delete this award?</span>                
    @Html.AntiForgeryToken()
    <span class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default btn-sm" onclick="closeFormOnButton('award', this)" />
        <input type="button" value="Cancel" class="btn btn-default btn-sm" onclick="closeFormOnButton('award__delete', this)" />
    </span>
}
</span>

Isdg/Views/Award/_Details.cshtml
@model Isdg.Core.Data.Award

<div class="award__details hidden">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
                
        <dt>
            @Html.DisplayNameFor(model => model.AddedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IP)
        </dd>

    </dl>
    <span class="form-actions no-color">        
        <input type="button" value="Cancel" class="btn btn-default btn-sm" onclick="closeFormOnButton('award__details', this)" />
    </span>
    <hr />
</div>

Isdg/Views/Award/_Edit.cshtml
@model Isdg.Core.Data.Award
<div class="award__edit hidden">
@*@using (Ajax.BeginForm("CreateEditAward", "Award", new AjaxOptions()
{
    UpdateTargetId = "award_id_" + Model.Id,
    OnComplete = "bindCkeditor()"
}))
{
    @Html.AntiForgeryToken()
    
    *@
    <div class="form-horizontal">        
        <hr />
        <form class="award__new">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => Model.Id)
        
        <div class="form-group">
            @Html.LabelFor(model => Model.Heading, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => Model.Heading, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => Model.Heading, "", new { @class = "text-danger" })
            </div>
        </div>
                        
        <div class="form-group">
            @Html.LabelFor(model => Model.Content, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => Model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => Model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group image">
            <label class="control-label col-md-2">Choose first image</label>
            <input type="file" class="award__image-upload-first form-control" data-index="0" accept="image/*" />
        </div>                          
        <div class="form-group image">
            <label class="control-label col-md-2">Choose second image (not required)</label>
            <input type="file" class="award__image-upload-second form-control" data-index="1" accept="image/*" />
        </div>
                
        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                <input type="button" value="Save" class="btn btn-default btn-sm award__submit" />
                <input type="button" value="Cancel" class="btn btn-default btn-sm" onclick="closeFormOnButton('award__edit', this)" />
            </div>
        </div>
        </form>
        <hr />
    </div>    
@*}*@
</div>